### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by qishenghu** [jongjyh/TrFr#2]
Could you kindly release the source code for this paper?

**Comment by ogencoglu** [comment]
+1

**Comment by jongjyh** [comment]
Hi, @ogencoglu @qishenghu 
Thanks for the interests in our work! Unfortunately, due to the company's open-source policy, we are currently unable to share the code.

**Comment by jongjyh** [comment]
We are recommending to follow the instruction described in the paper and  implement the TrFr with ITI codebase. 
Feel free to reach out if you have problem on replicate.

**Comment by ogencoglu** [comment]
@jongjyh  Why would you open a code repo then?

**Comment by jongjyh** [comment]
Hi, @ogencoglu  
Yes. We were planning to release the code under the instruction of AAAI. Unfortunately the final result came after that. While this repo could provide necessary help of replicating TrFr and we're working on negotiate potential code-releasing in the future.

**Comment by sev777** [comment]
++
