### ISSUE TITLE
What is the 'Random peek' setting in your ablation study?

### ISSUE THREAD

**Issue by Rainlt** [jongjyh/TrFr#3]
Hi, I'm very interested in your great work, but have some questions.

In the ablation study, does the 'Random peek' setting use more than one probes for one head? Or it is just like ITI with Random peek?

**Comment by jongjyh** [comment]
We use only one probe each head in ablation.

**Comment by Rainlt** [comment]
> We use only one probe each head in ablation.

ok, thank you~
